source 'http://rubygems.org'

ruby '~> 2.5.0'

gem 'openstudio-common-measures', '~> 0.3.2'
gem 'openstudio-model-articulation', '~> 0.3.1'
gem 'openstudio-load-flexibility-measures', '~> 0.2.1'
gem 'openstudio-ee', '~> 0.3.2'
gem 'openstudio-calibration', '~> 0.3.1'
gem 'urbanopt-geojson', '~> 0.5.3'
gem 'urbanopt-reporting', '~> 0.3.7'
